service: typescript-yarn-workspace

plugins:
  - serverless-webpack

provider:
  name: aws
  runtime: nodejs8.10
  region: eu-west-1

functions:
  first-function:
    handler: packages/server/src/handler.default
    events:
      - http:
          path: /
          method: get
