service: typescript-yarn-workspace

plugins:
  - serverless-webpack
  - serverless-offline

custom:
  serverless-offline:
    port: 4000

provider:
  name: aws
  runtime: nodejs12.x
  region: us-east-1

functions:
  first-function:
    handler: packages/server/src/handler.default
