version: 0.2

env:
  variables:
    ENVIRONMENT: "harry"
phases:
  install:
    commands:
      - echo $ENVIRONMENT
      - yarn
  build:
    commands:
      - yarn deploy
artifacts:
  files:
    - appspec.yml
  discard-paths: yes
